# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_utils/tensor_transmit/TensorTransmit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_utils/tensor_transmit/TensorTransmit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/grpc_utils/tensor_transmit/TensorTransmit.proto\x12\x0ftensor_transmit\"\x1c\n\x05Layer\x12\x13\n\x0blayer_index\x18\x01 \x01(\x05\"0\n\x0f\x41\x63tivationFloat\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0f\n\x07shape_f\x18\x02 \x03(\x05\"@\n\x0e\x41\x63tivationByte\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0f\n\x07shape_b\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t2\xb2\x01\n\x0eTensorTransmit\x12P\n\x12GetActivationFloat\x12\x16.tensor_transmit.Layer\x1a .tensor_transmit.ActivationFloat\"\x00\x12N\n\x11GetActivationByte\x12\x16.tensor_transmit.Layer\x1a\x1f.tensor_transmit.ActivationByte\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_utils.tensor_transmit.TensorTransmit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYER']._serialized_start=68
  _globals['_LAYER']._serialized_end=96
  _globals['_ACTIVATIONFLOAT']._serialized_start=98
  _globals['_ACTIVATIONFLOAT']._serialized_end=146
  _globals['_ACTIVATIONBYTE']._serialized_start=148
  _globals['_ACTIVATIONBYTE']._serialized_end=212
  _globals['_TENSORTRANSMIT']._serialized_start=215
  _globals['_TENSORTRANSMIT']._serialized_end=393
# @@protoc_insertion_point(module_scope)
